name: CMake Build Test ubuntu-latest

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Linux build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        run: if [ `builtin type -p cmake` ]; then echo cmake already installed; else sudo apt-get install cmake; fi

      - name: Install Ninja
        run: if [ `builtin type -p ninja` ]; then echo ninja already installed; else sudo apt-get install ninja-build; fi

      - name: Configure
        run: cmake -S .  -B build -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build ; ctest
